apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - license-secret-app.yaml  # License secret (must sync before gloo-mesh-mgmt)
  - gloo-mesh-mgmt.yaml       # Control plane in management cluster
  - gloo-mesh-east.yaml       # Data plane in east cluster
  - gloo-mesh-west.yaml       # Data plane in west cluster

